### ISSUE TITLE
detailed listings of students attempts

### ISSUE THREAD

**Issue by yoavfreund** [cse103/Attempt_Analysis#1]
All of the students incorrect attempts (excluding the universal ones: digits, previous part not answered, fraction, negative etc.) should be listed in full form, the way "nothing" atempts are listed right now.

**Comment by yoavfreund** [comment]
Each header should start with a number specifying how many cases are under this header (start with, because headers get chopped when using hide in emacs markdown.

The number is important so that the instructor can easily find the location where students had a lot of trouble.

**Comment by yoavfreund** [comment]
The form of the hint should be:
author,
condition,
hint.

The condition should be python code using the API we  designed for the conditional hints last year. The definition of this API, together with some examples, should be placed in a doc directory accessible to the instructor.

**Comment by zhenzhai** [comment]
Decided not to do this after discussion in meeting today.
